registers the .mlt file name extension and associate it with shotcut.exe
mltframework/shotcut pull request #1237
Opened 2022-03-04 06:24 UTC by timlau

I have added initial .mlt file assoiation to the windows NSIS installer

I don't have a windows system to test on at the moment, but is be easy to test and not break anything

2022-03-04 22:49 UTC, ddennedy commented on packaging/windows/shotcut.nsi
> +  DeleteRegStr HKCR "Shotcut\shell\open\command"
> Invalid command: "DeleteRegStr"

Should be `DeleteRegKey`

2022-03-04 22:55 UTC, ddennedy requested changes
Thanks for your contribution! I can confirm it is working with some small changes.

2022-03-04 22:55 UTC, ddennedy commented on packaging/windows/shotcut.nsi
> + WriteRegStr HKCR "Shotcut\shell\open\command" "" "$\"$INSTDIR\shotcut.exe$\" $\"%1$\""
change indentation to 2 spaces please

2022-03-04 22:55 UTC, ddennedy commented on packaging/windows/shotcut.nsi
> +  DeleteRegStr HKCR "Shotcut\shell\open\command"
Also, `DeleteRegStr HKCR "Shotcut\shell\open\command"`
should be `DeleteRegKey HKCR "Shotcut"` to delete the whole subtree we created.

2022-03-05 06:48 UTC, timlau commented
I have solved the issues and made a minor change to the naming uses Shotcut.mlt instead of Shortcut, It is the naming style than most application uses. Ex. .7z uses 7Zip,7z

2022-03-05 07:35 UTC, ddennedy commented
> change to the naming uses Shotcut.mlt 

OK, yes I see that too in registy, but then I thought how with the "Type" appear in Explorer? I do not want it to show "Shotcut.mlt". I looked in Explorer, and I see it is showing "MLT XML," but I cannot find that anywhere in the registry?! Where is it getting this. I needed to uninstall the Microsoft Store app to test this properly. Ah, I see in my AppxManifest.xml to make the store app, I register the file association and set the "DisplayName" to MLT XML along with a logo.

![image](https://user-images.githubusercontent.com/1146683/156873580-55454c7c-1a86-46a2-b77c-24a083f89903.png)


It must be caching that info somewhere. Well, I am not going to reboot just to see if that changes things.

2022-03-05 07:36 UTC, merged