refactor: remove QString::number() in arg() arguments
mltframework/shotcut pull request #1604
Opened 2024-11-06 04:40 UTC by Integral-Tech

- `QString::arg()` has overload for numeric data types, hence it is unnecessary to use `QString::number()` in `QString::arg()` arguments.

2024-11-06 23:20 UTC, ddennedy requested changes
Looks good except that one mistake.

2024-11-06 23:20 UTC, ddennedy commented on src/widgets/scopes/audiowaveformscopewidget.cpp
> +                .arg(dbValue, 0, 'f', 1);
This has the incorrect precision of 1.

2024-11-07 02:06 UTC, Integral-Tech commented on src/widgets/scopes/audiowaveformscopewidget.cpp
> +                .arg(dbValue, 0, 'f', 1);
Oh, sorry :(

2024-11-07 02:08 UTC, Integral-Tech commented
@ddennedy Fixed :)

2024-11-07 02:58 UTC, merged